---
- name: Restart wayvnc
  become: true
  ansible.builtin.systemd:
    name: wayvnc
    state: restarted

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Rescan DMS plugins
  ansible.builtin.command: dms ipc plugin-scan scan
  failed_when: false
  changed_when: false
