---
- name: Restart wayvnc
  become: true
  ansible.builtin.systemd:
    name: wayvnc
    state: restarted

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
